// @ts-check
// Generated by scripts/draw_fauna.py from the same numbers that drew
// assets/critters.svg. Do not edit; change the script and re-run it.

/**
 * Flip-books for the rest of the neighbourhood, on the roadrunner's
 * scheme (see fauna-data.js): `--frame` 0..runFrames-1 is the gait,
 * `stand` is at rest, and one gait cycle covers `cycle` viewBox units.
 * The toad hops instead: `crouch` and `leap` are its frames, and a hop
 * is `hop` units long and `hopHeight` high.
 * @type {Record<string, { viewBox: number[], stand: number, pivot: number, runFrames?: number, cycle?: number,
 *   crouch?: number, leap?: number, hop?: number, hopHeight?: number }>}
 */
export const CRITTERS = {"javelina": {"viewBox": [0, 0, 127, 72], "runFrames": 6, "stand": 6, "cycle": 40, "pivot": 0.3465}, "rattlesnake": {"viewBox": [0, 0, 182, 23], "runFrames": 6, "stand": 6, "cycle": 56, "pivot": 0.522}, "scorpion": {"viewBox": [0, 0, 100, 60], "runFrames": 6, "stand": 6, "cycle": 16, "pivot": 0.42}, "toad": {"viewBox": [0, 0, 85, 46], "stand": 6, "crouch": 0, "leap": 1, "hop": 50, "hopHeight": 15, "pivot": 0.5882}};
