// @ts-check
// Generated by scripts/draw_fauna.py from the same numbers that drew
// assets/fauna.svg. Do not edit; change the script and re-run it.

/**
 * The roadrunner flip-book. `--frame` 0..runFrames-1 is the run cycle,
 * `stand` and `flick` the standing poses; one whole cycle carries the
 * bird `cycle` units (its own viewBox units) along the ground; it turns
 * around at `pivot` (a fraction of its width: the hip).
 * @type {{ viewBox: number[], runFrames: number, stand: number, flick: number, cycle: number, pivot: number }}
 */
export const ROADRUNNER = {"viewBox": [0, -13, 176, 115], "runFrames": 6, "stand": 6, "flick": 7, "cycle": 73.913, "pivot": 0.5341};
