// @ts-check
// Generated by scripts/build_terrain.py. Do not edit by hand: change the
// script and re-run it, which rewrites this file and the heightmap together.
// Elevation: USGS 3DEP via AWS Terrain Tiles. Summits: USGS GNIS / NGS, NAVD 88.

/** @type {import('./arizona.js').Terrain} */
export const TERRAIN = {
  src: "assets/terrain/heightmap.webp",
  cols: 662,
  rows: 679,
  west: -112.042,
  south: 33.459,
  east: -111.928,
  north: 33.557,
  elevLoM: 335,
  elevHiM: 815,
  mPerDegLat: 110913.5,
  mPerDegLon: 92914.0,
  focus: { lat: 33.514724, lon: -111.961604 },
  peaks: [
    { name: "Camelback Mtn", lat: 33.514724, lon: -111.961604, feet: 2706, radiusM: 1400 },
    { name: "Piestewa Peak", lat: 33.547332, lon: -112.020989, feet: 2610, radiusM: 1100 },
    { name: "Mummy Mtn", lat: 33.543654, lon: -111.960424, feet: 2260, radiusM: 1000 },
  ],
};
